name: Build Blob Composite Action

description: >-
  A composite action that is placed in ./.github/actions/build-blob/action.yaml whereby
  ./github/workflows/cw-build-blob.yaml will trigger this action to build the blob(s).
  The steps can be adjusted per the user's need just as long as the blob artifact(s) are
  referenced for downstream jobs.

runs:
  using: composite
  steps:
    - name: Build Blob
      shell: bash
      run: |
        echo "i am a blob being created at $(date +'%Y-%m-%d %H:%M:%S') by ${{ github.triggering_actor }} by rw of
        ${{ github.workflow_ref }} in the repo of ${{ github.repository }} by the action known as ${{ github.action }}." > i_am_blob &&
        echo "i am another blob being created at $(date +'%Y-%m-%d %H:%M:%S') by ${{ github.triggering_actor }} by rw of
        ${{ github.workflow_ref }} in the repo of ${{ github.repository }}" > i_am_another_blob
