name: gimme teh 🤫 🥫

on:
  workflow_call:
    inputs:
      subject-name:
        required: true
        type: string
      cert-identity:
        required: true
        type: string

env:
  GH_TOKEN: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}

jobs:
  get-teh-sauce1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - run: ls -alt .github/actions/* .github/workflows
      - name: Checkout external repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          repository: liatrio/demo-gh-autogov-workflows
          ref: main
          path: demo-gh-autogov-workflows
          token: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}
      - run: ls -alt .github/actions/* .github/workflows ./demo-gh-autogov-workflows/.github/actions/* ./demo-gh-autogov-workflows/.github/workflows/*
      - name: Run action from external repo
        uses: ./demo-gh-autogov-workflows/.github/actions/build-image
        with:
          input-name: ${{ inputs.subject-name }}
      - name: Call another workflow
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'liatrio',
              repo: 'demo-gh-autogov-workflows',
              workflow_id: 'rw-hp-build-image.yaml',
              ref: 'main',
              inputs: {
                'subject-name': '${{ inputs.subject-name }}',
                'cert-identity': '${{ inputs.cert-identity }}'
              }
            })
