name: gimme teh 🤫 🥫

on:
  workflow_dispatch:
    inputs:
      subject-name:
        required: true
        type: string
      cert-identity:
        required: true
        type: string
env:
  GH_TOKEN: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}

jobs:
  get-teh-sauce:
    runs-on: ubuntu-latest
    steps:
      - name: get teh sauce
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          repository: liatrio/demo-gh-autogov-workflows
          ref: main
          token: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}
      - name: run teh sauce
        uses: ./.github/workflows/rw-hp-build-image.yaml
        with:
          subject-name: ${{ inputs.subject-name }}
          cert-identity: ${{ inputs.cert-identity }}
