name: gimme teh 🤫 🥫

on:
  workflow_call:
    inputs:
      subject-name:
        required: true
        type: string
      cert-identity:
        required: true
        type: string
env:
  GH_TOKEN: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}

jobs:
  get-teh-sauce:
    uses: liatrio/rw-puller-repo/.github/workflows/secret-sauce.yaml@main
    secrets: inherit
    with:
      subject-name: ghcr.io/${{ github.repository }}
      cert-identity: https://github.com/liatrio/rw-puller-repo/.github/workflows/secret-sauce.yaml@main
