name: gimme teh 🤫 🥫

on:
  workflow_call:
    inputs:
      subject-name:
        required: true
        type: string
      cert-identity:
        required: true
        type: string
env:
  GH_TOKEN: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}

jobs:
  get-teh-sauce1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - run: ls -alt .github/actions/*
      - name: get teh sauce
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          repository: liatrio/demo-gh-autogov-workflows
          ref: main
          path: demo-gh-autogov-workflows
          token: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}
      - run: |
            ls -alt .github/actions/*
            ls -alt .github/workflows
            ls -alt ./demo-gh-autogov-workflows/.github/actions/*
            ls -alt ./demo-gh-autogov-workflows/.github/workflows/*
      - name: run teh sauce 1
        uses: ./demo-gh-autogov-workflows/.github/workflows/rw-hp-attest-image.yaml
        with:
          subject-name: ${{ inputs.subject-name }}
          cert-identity: ${{ inputs.cert-identity }}
  get-teh-sauce2:
    runs-on: ubuntu-latest
    steps:
      - name: run teh sauce 2
        uses: ./demo-gh-autogov-workflows/.github/workflows/rw-hp-verify.yaml
        with:
          build-type: image
          image-digest: ${{ needs.get-teh-sauce1.outputs.image-digest }}
          cert-identity: ${{ inputs.cert-identity }}
  get-teh-sauce3:
    runs-on: ubuntu-latest
    steps:
      - name: run teh sauce 3
        uses: ./demo-gh-autogov-workflows/.github/workflows/rw-hp-run-opa.yaml
        with:
          build-type: image
          image-digest: ${{ needs.get-teh-sauce1.outputs.image-digest }}
          subject-name: ${{ inputs.subject-name }}
          cert-identity: ${{ inputs.cert-identity }}
